name: Trantor Deploy

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    name: Build and release
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    # - name: Set up Elixir
    #   uses: ximes/setup-elixir@v1.6.0
    #   with:
    #     otp-version: '22'
    #     elixir-version: '1.7.4'
    # - name: Restore dependencies cache
    #   uses: actions/cache@v2
    #   with:
    #     path: deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    #     restore-keys: ${{ runner.os }}-mix-
    - run: mix local.rebar --force && mix local.hex --force
    - run: mix deps.get && mix deps.compile && mix compile
    - name: Compiling assets
      run: cd assets && yarn install && yarn deploy && cd - && mix phx.digest
    - name: Stopping current Release
      run: /opt/cogsworth/bin/cogsworth stop
      continue-on-error: true
    - name: Preparing Release
      run: SECRET_KEY_BASE=q9/imeo1YRsGmQ0MFLjpFxnQZGUtyPjNhQbSJnUJ7SBfykSE70CG3xXY5kEQ4Dr5 MIX_ENV=prod mix release
    - name: Copying release
      run: cp -r _build/prod/rel/cogsworth/* /opt/cogsworth/
    - name: Release
      run: /opt/cogsworth/bin/cogsworth daemon_iex

